// 商品种子数据（与 frontend/src/mock/products.ts 保持一致）
// 图片使用 picsum 占位图

const img = (seed: string) => `https://picsum.photos/seed/${seed}/600/600`

export interface SeedProduct {
  id: number
  name: string
  price: number
  description: string
  category: string
  image_url: string
  stock: number
  tags: string[]
  created_at: string
}

export const seedProducts: SeedProduct[] = [
  {
    id: 1,
    name: 'SoundWave Pro 主动降噪耳机',
    price: 899,
    description:
      '采用主动降噪技术，40mm 大动圈单元，续航可达 30 小时。支持蓝牙 5.3，佩戴舒适，适合长时间使用。',
    category: '耳机',
    image_url: img('headphone1'),
    stock: 50,
    tags: ['降噪', '蓝牙', '长续航'],
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 2,
    name: 'BassMax X1 入耳式运动耳机',
    price: 199,
    description: 'IPX7 级防水，专为运动设计。低音浑厚，佩戴稳固，附带多副耳塞套。',
    category: '耳机',
    image_url: img('earphone1'),
    stock: 120,
    tags: ['运动', '防水', '入耳式'],
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 3,
    name: 'AirTune Lite 真无线蓝牙耳机',
    price: 399,
    description: '真无线设计，单次续航 6 小时，配合充电盒可达 24 小时。支持触控操作。',
    category: '耳机',
    image_url: img('earbuds1'),
    stock: 80,
    tags: ['真无线', '触控', '便携'],
    created_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 4,
    name: 'MechanicalKey K8 机械键盘',
    price: 459,
    description:
      '87 键紧凑布局，热插拔轴体，RGB 背光。可选红轴/茶轴/青轴，铝合金面板，做工扎实。',
    category: '键盘',
    image_url: img('keyboard1'),
    stock: 60,
    tags: ['机械', '热插拔', 'RGB'],
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 5,
    name: 'TypeWriter V2 复古机械键盘',
    price: 699,
    description: '复古打字机造型，圆形键帽，青轴手感清脆。蓝牙/有线双模，支持多设备切换。',
    category: '键盘',
    image_url: img('keyboard2'),
    stock: 35,
    tags: ['复古', '双模', '青轴'],
    created_at: '2026-02-10T08:00:00Z',
  },
  {
    id: 6,
    name: 'GamerKey RGB 电竞机械键盘',
    price: 329,
    description: '104 键全尺寸，RGB 幻彩背光，红轴线性手感。带多媒体按键和手托。',
    category: '键盘',
    image_url: img('keyboard3'),
    stock: 90,
    tags: ['电竞', 'RGB', '红轴'],
    created_at: '2026-01-25T08:00:00Z',
  },
  {
    id: 7,
    name: 'ErgoMouse M3 人体工学鼠标',
    price: 159,
    description: '垂直人体工学设计，有效缓解手腕疲劳。6 个可编程按键，DPI 最高 4000。',
    category: '鼠标',
    image_url: img('mouse1'),
    stock: 100,
    tags: ['人体工学', '无线', '办公'],
    created_at: '2026-01-18T08:00:00Z',
  },
  {
    id: 8,
    name: 'GamerMouse G7 电竞鼠标',
    price: 249,
    description: 'PMW3360 传感器，DPI 高达 12000。7 个可编程按键，RGB 灯效，重量仅 85g。',
    category: '鼠标',
    image_url: img('mouse2'),
    stock: 70,
    tags: ['电竞', '高DPI', '轻量'],
    created_at: '2026-02-05T08:00:00Z',
  },
  {
    id: 9,
    name: 'SilentClick S1 静音鼠标',
    price: 89,
    description: '静音点击设计，办公不扰人。2.4G 无线连接，续航 12 个月。',
    category: '鼠标',
    image_url: img('mouse3'),
    stock: 150,
    tags: ['静音', '无线', '办公'],
    created_at: '2026-01-30T08:00:00Z',
  },
  {
    id: 10,
    name: 'UltraView 27 英寸 4K 显示器',
    price: 2199,
    description: '27 英寸 IPS 面板，4K 超高清分辨率，99% sRGB 色域。Type-C 一线连，支持 65W 反向充电。',
    category: '显示器',
    image_url: img('monitor1'),
    stock: 25,
    tags: ['4K', 'IPS', 'Type-C'],
    created_at: '2026-01-12T08:00:00Z',
  },
  {
    id: 11,
    name: 'GamerView 240Hz 电竞显示器',
    price: 1899,
    description: '24.5 英寸 TN 面板，240Hz 刷新率，1ms 响应时间。支持 G-Sync，FPS 游戏利器。',
    category: '显示器',
    image_url: img('monitor2'),
    stock: 18,
    tags: ['240Hz', '电竞', '1ms'],
    created_at: '2026-02-08T08:00:00Z',
  },
  {
    id: 12,
    name: 'PortableView 15.6 便携显示器',
    price: 799,
    description: '15.6 英寸 IPS，1080P 分辨率。轻薄便携，Type-C/HDMI 双接口，外出办公好帮手。',
    category: '显示器',
    image_url: img('monitor3'),
    stock: 40,
    tags: ['便携', 'IPS', 'Type-C'],
    created_at: '2026-01-22T08:00:00Z',
  },
  {
    id: 13,
    name: 'SmartWatch W5 智能手表',
    price: 599,
    description: '1.43 英寸 AMOLED 屏，支持心率、血氧、睡眠监测。50+ 运动模式，IP68 防水。',
    category: '智能穿戴',
    image_url: img('watch1'),
    stock: 65,
    tags: ['智能手表', '健康监测', '防水'],
    created_at: '2026-02-12T08:00:00Z',
  },
  {
    id: 14,
    name: 'FitBand B3 智能手环',
    price: 199,
    description: '1.1 英寸彩屏，24 小时心率监测，14 天超长续航。支持 100+ 运动模式。',
    category: '智能穿戴',
    image_url: img('band1'),
    stock: 200,
    tags: ['手环', '长续航', '运动'],
    created_at: '2026-01-28T08:00:00Z',
  },
  {
    id: 15,
    name: 'DeskLamp D1 智能护眼台灯',
    price: 299,
    description: '国 AA 级照度，无频闪无蓝光危害。触控调光调色，支持手机无线充电底座。',
    category: '家居',
    image_url: img('lamp1'),
    stock: 85,
    tags: ['护眼', '无线充电', '触控'],
    created_at: '2026-02-15T08:00:00Z',
  },
  {
    id: 16,
    name: 'PowerBank P2 磁吸无线充电宝',
    price: 169,
    description: '10000mAh 大容量，MagSafe 磁吸无线充，20W 有线快充。轻薄便携。',
    category: '配件',
    image_url: img('powerbank1'),
    stock: 110,
    tags: ['磁吸', '无线充', '快充'],
    created_at: '2026-01-16T08:00:00Z',
  },
  {
    id: 17,
    name: 'HubStation H1 扩展坞',
    price: 349,
    description: '11 合 1 扩展坞，支持 4K HDMI、SD/TF 读卡、USB 3.0、千兆网口、PD 100W 快充。',
    category: '配件',
    image_url: img('hub1'),
    stock: 55,
    tags: ['扩展坞', '4K', 'PD快充'],
    created_at: '2026-02-03T08:00:00Z',
  },
  {
    id: 18,
    name: 'WebCam C2 高清摄像头',
    price: 229,
    description: '2K 高清画质，自动对焦，内置双麦克风降噪。即插即用，网课会议好帮手。',
    category: '配件',
    image_url: img('webcam1'),
    stock: 75,
    tags: ['2K', '自动对焦', '麦克风'],
    created_at: '2026-01-14T08:00:00Z',
  },
  {
    id: 19,
    name: 'SpeakerMini S1 蓝牙音箱',
    price: 179,
    description: '360° 环绕音效，IPX7 防水，续航 12 小时。支持 TWS 串联，户外派对必备。',
    category: '音箱',
    image_url: img('speaker1'),
    stock: 95,
    tags: ['蓝牙', '防水', '便携'],
    created_at: '2026-02-18T08:00:00Z',
  },
  {
    id: 20,
    name: 'StudioSound X3 桌面音箱',
    price: 549,
    description: '2.0 声道 HiFi 音质，木质箱体，蓝牙 5.0/有线双输入。桌面影音享受。',
    category: '音箱',
    image_url: img('speaker2'),
    stock: 40,
    tags: ['HiFi', '木质', '蓝牙'],
    created_at: '2026-01-08T08:00:00Z',
  },
]
